["Basic pattern-less correlation"]
start = "this is the start"
end = "end over"

["Correlation using a pattern"]
start = "starting request (\d+)"
end = "request (\d+) ended."
debug = true # adds some extra verbosity, useful when making new rules
