from _typeshed import Incomplete

def lex(code, lexer): ...
def format(tokens, formatter, outfile: Incomplete | None = ...): ...
def highlight(code, lexer, formatter, outfile: Incomplete | None = ...): ...
